/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOracle } from "./IOracle";
export type { ISoulbound } from "./ISoulbound";
export type { IWorldID } from "./IWorldID";
