/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Guild } from "./Guild";
export type { Soulbound } from "./Soulbound";
export type { TestOracle } from "./TestOracle";
